<a href='https://www.darshan.ac.in/'> <img src='https://www.darshan.ac.in/Content/media/DU_Logo.svg' width="250" height="300"/></a>
<pre>
<center><b><h1>Machine Learning - 2301CS621</b></center>

<center><b><h1>Lab - 1</b></center>    
<pre>    

# NumPy Exercises
## We'll start off with a few simple tasks

## import numpy as np

### What is NumPy? (5 Key Points)

1. **Core Purpose**: NumPy (Numerical Python) is the foundational library for numerical and scientific computing in Python.
2. **N-Dimensional Arrays (`ndarray`)**: Its central feature is the powerful, highly efficient multidimensional array object. Unlike standard Python lists, these arrays hold items of the same type and allow for fast, vectorized mathematical operations.
3. **High Performance**: Because its core operations are implemented in C, NumPy is incredibly fast. It executes complex computations on large datasets much more efficiently than standard Python loops and lists.
4. **Rich Mathematical Toolkit**: It provides a vast collection of built-in mathematical, logical, shape manipulation, sorting, and basic statistical operations that can be applied to entire arrays without needing explicit loops.
5. **Foundation of the Ecosystem**: NumPy serves as the bedrock for almost the entire Python data science and machine learning ecosystem. Popular libraries like Pandas, SciPy, scikit-learn, and TensorFlow are built on top of it or rely heavily on its array structures.


In [2]:
import numpy as np

In [58]:
n = np.array([1,2,3,4],dtype=str)

In [59]:
type(n)

numpy.ndarray

In [60]:
n

array(['1', '2', '3', '4'], dtype='<U1')

In [61]:
n.dtype

dtype('<U1')

## Create an array of 10 zeros

In [62]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

## Create an array of 10 ones

In [63]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [64]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## Create an array of 10 fives

In [65]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [66]:
np.ones([5,5])*2

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

## Create an array of the integers from 10 to 50

In [67]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [68]:
np.arange(0,51,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

## Create a 3x3 matrix with values ranging from 0 to 8

In [69]:
np.arange(0,9,1).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## Create a 3x3 identity matrix

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [71]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Create following matrix  = <br/>
<pre>array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])</pre>

In [72]:
n =np.arange(1,26,1).reshape(5,5)

In [73]:
n

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

## Output should be =
<pre>array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])</pre>

In [78]:
n[2::, 1::]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [77]:
n[1::2,1::2]

array([[ 7,  9],
       [17, 19]])

## Output should be = <br/>
<pre>array([[ 2],
       [ 7],
       [12]])</pre>

In [ ]:
n[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

## Find Odd Numbers
Extract all odd numbers from `arr`.

`arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])` <BR>
Use Condtional Selection

In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
odd_numbers = arr[arr % 2 == 1]

print(odd_numbers)

[1 3 5 7 9]


In [8]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
odd_numbers = arr[arr % 2 == 0]
print(odd_numbers)

[0 2 4 6 8]


## Stacking
Stack array `a` and `b` vertically.

`a = np.arange(10).reshape(2,-1)`
`b = np.repeat(1, 10).reshape(2,-1)`

In [ ]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
output = np.vstack([a, b])
print(output)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


##  Range Filtering
Get all items between 5 and 10 from `a`.

`a = np.array([2, 6, 1, 9, 10, 3, 27])`

In [14]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
output = a[(a >= 5) & (a <= 10)]
print(output)

[ 6  9 10]


## Matrix Multiplication
Multiply a 5x3 matrix by a 3x2 matrix (dot product).

In [15]:
A = np.random.random((5,3))
B = np.random.random((3,2))
product = np.dot(A, B)
print(product)

[[0.64776098 0.47601452]
 [0.56571167 1.14254961]
 [1.06701087 0.87866572]
 [0.46701213 0.90352742]
 [0.75243227 0.79906774]]


# Great Job! You’re Halfway Through 🚀  | PANDAS  Exercises



### Step 1. Import the necessary libraries

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user). 

### Step 3. Assign it to a variable called users and use the 'user_id' as index

### Step 4. See the first 25 entries

### Step 5. See the last 10 entries

### Step 6. What is the number of observations in the dataset?

### Step 7. What is the number of columns in the dataset?

### Step 8. Print the name of all the columns.

### Step 9. How is the dataset indexed?

In [ ]:
# "the index" (aka "the labels")


### Step 10. What is the data type of each column?

### Step 11. Print only the occupation column

### Step 12. How many different occupations are in this dataset?

### Step 13. What is the most frequent occupation?

### Step 14. Summarize the DataFrame.

### Step 15. Summarize all the columns

### Step 16. Summarize only the occupation column

### Step 17. What is the mean age of users?

### Step 18. What is the age with least occurrence?